//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlyNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    using QlyNhaHang.Models;
    using System.ComponentModel.DataAnnotations; 
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderPro = new HashSet<OrderPro>();
        }


        [Display(Name = "ID")]
        public int IDCus { get; set; }
        [Required(ErrorMessage = "This file is empty")]
        [Display(Name = "Name")]
        public string NameCus { get; set; }
        [Required(ErrorMessage = "This file is empty")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "So dien thoai phai co 10 so ")]
        [Display(Name = "Phone")]
        public string PhoneCus { get; set; }
        [Required(ErrorMessage = "This file is empty")]
        [EmailAddress(ErrorMessage = "Dia Chi email khong hop le")]
        [Display(Name = "Email")]
        public string EmailCus { get; set; }
        [Required(ErrorMessage = "This file is empty")]
        [Display(Name = "Username")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "This file is empty")]
        [RegularExpression(@"[a-zA-Z].*", ErrorMessage = "Mat khau bat dau bang chu cai")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Mat khau phai co do dai tu 6 den 20")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "This file is empty")]
        [Display(Name = "Repassword")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirm Password Doesn't Match")]
        public string RePassword { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderPro { get; set; }
    }
}
